version: '3.1'

services:

  db:
    image: mysql
    restart: always
    ports: 
      - 3306:3306  # MySQL default port
    environment:
      MYSQL_ROOT_PASSWORD: example # Change this to a secure password
      MYSQL_DATABASE: hostel
      MYSQL_USER: root # Optional: Specify a user if you don't want to use root
      MYSQL_PASSWORD: password # Optional: Password for the new user

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080